<?php 

/* RULES FOR POSTING TO DATABASE
  DATABASE HAS 3 TABLES: EXAMS, COURSES, DATES

  IF YOU INSERT INTO EXAMS BEFORE COURSES / DATES THEN THINGS BREAK
  DONT BE THE GUY WHO BREAKS THE DATABASE AND INSERT DATA PROPERLY

  exams.exam_name uses a trigger function to update the column
  NEVER LIST 'exam_name' AS A COLUMN YOU ARE INSERTING INTO
  LET IT POPULATE ITSELF AUTOMATICALLY AND THINGS WILL BE OK

*/
  

  function postExamMain($request) {
    $request
    
  }
?>